agenda/urls.py
from django.urls import path
from . import views
from .views import AgendaListView, AgendaCreateView, AgendaUpdateView, AgendaDeleteView

urlpatterns = [
    path('', AgendaListView.as_view(), name='lista'),
    path('cadastrar/', AgendaCreateView.as_view(), name='cadastrar'),
    path('atualizar/<int:pk>', AgendaUpdateView.as_view(), name='atualizar'),
    path('deletar/<int:pk>', AgendaDeleteView.as_view(), name='deletar'),
    path('person/json1/', views.cadastro_json1, name='cadastro_json1'),
    path('estado/cidadte/selected/', views.update_select_cidade, name='update_select_cidade'),
]

projagenda/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('agenda.urls')),
    path('admin/', admin.site.urls),
]

agenda/models.py
from django.db import models


class Estado(models.Model):
    nom_estado = models.CharField(max_length=255)
    sgl_estado = models.CharField(max_length=2)

    class Meta:
        db_table = 'estado'

    def __str__(self):
        return self.nom_estado


class Cidade(models.Model):
    nom_cidade = models.CharField(max_length=255)
    cod_estado = models.ForeignKey(Estado, on_delete=models.CASCADE)

    class Meta:
        ordering = ('nom_cidade',)
        db_table = 'cidade'

    def __str__(self):
        return self.nom_cidade

class Cadastro(models.Model):
    nome = models.CharField(max_length=100, verbose_name="Nome")
    sobrenome = models.CharField(max_length=100, verbose_name="Sobrenome")
    email = models.EmailField(verbose_name="E-mail")
    endereco = models.CharField(max_length=255, verbose_name="Endereço")
    cargo = models.CharField(max_length=100, verbose_name="Cargo")
    celular = models.CharField(max_length=9, verbose_name="Celular")
    telefone = models.CharField(max_length=9, verbose_name="Tel.Fixo")
    SEXO = (
        ('HOMEM', 'Homem'),
        ('MULHER', 'Mulher'),
    )
    sexo = models.CharField(max_length=6, choices=SEXO)
    estado_fk = models.ForeignKey(Estado, on_delete=models.PROTECT,
                                  null=True, blank=True)
    cidade_fk = models.ForeignKey(Cidade, on_delete=models.PROTECT,
                                  null=True, blank=True)

    class Meta:
        ordering = ('nome',)
        verbose_name = 'cadastro'
        verbose_name_plural = 'cadastros'

    def __str__(self):
        return self.nome

    def to_dict_json(self):
        return {
            'pk': self.pk,
            'nome': self.nome,
            'email': self.email,
            'telefone': self.telefone,
            'celular': self.celular,
        }

agenda/forms.py
from django import forms
from .models import Cadastro, Cidade


class CadastroForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CadastroForm, self).__init__(*args, **kwargs)
        self.fields['cidade_fk'].queryset = Cidade.objects.none()

        # hack para funcionar com modelform
        if 'estado_fk' in self.data:
            try:
                estado_fk = int(self.data.get('estado_fk'))
                self.fields['cidade_fk'].queryset = Cidade.objects.filter(cod_estado=estado_fk).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['cidade_fk'].queryset = self.instance.estado_fk.cidade_fk_set.order_by('name')

    class Meta:
        model = Cadastro
        fields = ('nome', 'sobrenome', 'email', 'endereco', 'sexo', 'telefone', 'celular',
                  'cargo', 'estado_fk', 'cidade_fk')
        widgets = {
            'nome': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'sobrenome': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'email': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'endereco': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'sexo': forms.Select(attrs={
                'class': 'custom-select form-control', }
            ),
            'telefone': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'celular': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'cargo': forms.TextInput(attrs={
                'class': 'form-control',
                'type': 'text',
            }),
            'estado_fk': forms.Select(attrs={
                'class': 'custom-select form-control', }
            ),
            'cidade_fk': forms.Select(attrs={
                'class': 'custom-select form-control', }
            ),
        }

agenda/views.py
from django.template.loader import render_to_string
from django.views.generic.list import ListView
from django.views.generic import CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import CadastroForm
from .models import Cadastro, Cidade
from django.http import JsonResponse


class AgendaCreateView(CreateView):
    form_class = CadastroForm
    template_name = "cadastrar.html"
    model = Cadastro
    success_url = reverse_lazy("lista")


class AgendaListView(ListView):
    template_name = "lista.html"
    model = Cadastro
    context_object_name = "cadastros"
    query_results = Cadastro.objects.all()


class AgendaUpdateView(UpdateView):
    form_class = CadastroForm
    template_name = "atualizar.html"
    model = Cadastro
    success_url = reverse_lazy("lista")


class AgendaDeleteView(DeleteView):
    form_class = CadastroForm
    template_name = "deletar.html"
    model = Cadastro
    context_object_name = "deletar"
    success_url = reverse_lazy("lista")


def cadastro_json1(request):
    cadastros = Cadastro.objects.all()
    data = [cadastro.to_dict_json() for cadastro in cadastros]
    response = {'data': data}
    return JsonResponse(response)


def update_select_cidade(request):
    data = {}
    state = request.GET.get('state')
    if state:
        cities = Cidade.objects.filter(cod_estado__pk=state)
        data['html_cidade_option'] = render_to_string(
            'select_cidade_estado_option.html', context={'cities': cities}, request=request)

    return JsonResponse(data)

agenda/templates/atualizar.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}


{% block breadcrumbs %}
    {{ block.super }}
    
{% endblock %}
{% block content %}

<div class="d-flex justify-content-center align-items-center container ">
  <div class="col-md-5 col-md-offset-5" style="margin: 3% 0">
    <form method="post">
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="{{form.name.id_for_label}}">Nome:</label>
          <div>{{ form.nome }}</div>
        </div>
        <div class="form-group col-md-6">
          <label for="{{form.sobrenome.id_for_label}}">Sobrenome:</label>
          <div>{{ form.sobrenome }}</div>
        </div>
      </div>
      <div class="form-group">
        <label for="{{form.email.id_for_label}}">E-mail:</label>
        <div>{{ form.email }}</div>
      </div>
      <div class="form-group">
        <label for="{{form.endereco.id_for_label}}">Endereço:</label>
        <div>{{ form.endereco }}</div>
        <small id="emailHelp" class="form-text text-muted">Ex.: Rua Dezoito, Numero 181, Bairro Tropical, Contagem</small>
      </div>
      <div class="form-group">
        <label for="{{form.celular.id_for_label}}">Celular:</label>
        <div>{{ form.celular }}</div>
      </div>
      <div class="form-group">
        <label for="{{form.telefone.id_for_label}}">Tel.Fixo:</label>
        <div>{{ form.telefone }}</div>
      </div>
      <div class="form-group">
        <label for="{{form.cargo.id_for_label}}">Cargo:</label>
        <div>{{ form.cargo }}</div>
      </div>
      <div class="form-group">
        <label for="{{form.sexo.id_for_label}}">Sexo:</label>
        <div>{{ form.sexo }}</div>
      </div>
      {% csrf_token %}
      <a href="{% url 'lista' %}" class="btn btn-secondary">Voltar</a>
      <button class="btn btn-primary">Atualizar</button>
    </form>
  </div>
</div>
{% endblock %}

agenda/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon.ico'%}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">

        <!-- Font-awesome -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
        <title>{% block title %}Agenda{% endblock title %}</title>
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/">Agenda</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
            <a class="nav-link" href="/">Listar</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'cadastrar' %}">Cadastrar</a>
            </li>
        </ul>
        </div>
        <form class="form-inline my-2 my-lg-0">
            <h4>{{user.get_full_name}}</h4>
        </form>
    </nav>
    
    {% block content %}{% endblock %}

    {% block javascript %}{% endblock %}
    </body>
</html>

agenda/templates/cadastrar.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
<title>{% block title %} {{block.super}} - Cadastro {%endblock%}</title>
{% block breadcrumb %}<li class="breadcrumb-item active" aria-current="page">Cadastro</li>{% endblock %}
{% block content %}
<div class="d-flex justify-content-center align-items-center container ">
  <div class="col-md-5 col-md-offset-5" style="margin: 3% 0">
    <form method="post">
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="{{form.name.id_for_label}}">Nome:</label>
          <div>{{ form.nome }}</div>
        </div>
        <div class="form-group col-md-6">
          <label for="{{form.sobrenome.id_for_label}}">Sobrenome:</label>
          <div>{{ form.sobrenome }}</div>
        </div>
    </div>
      <div class="form-group">
          <label for="{{form.email.id_for_label}}">E-mail:</label>
          <div>{{ form.email }}</div>
        </div>
      <div class="form-group">
        <label for="{{form.endereco.id_for_label}}">Endereço:</label>
        <div>{{ form.endereco }}</div>
        <small id="Help" class="form-text text-muted">Ex.: Rua Dezoito, Numero 181, Bairro Tropical, Contagem</small>
      </div>
      <div class="form-group">
        <label for="{{form.celular.id_for_label}}">Celular:</label>
        <div>{{ form.celular }}</div>
      </div>
      <div class="form-group">
        <label for="{{form.telefone.id_for_label}}">Tel.Fixo:</label>
        <div>{{ form.telefone }}</div>
      </div>
      <div class="form-group">
        <label for="{{form.cargo.id_for_label}}">Cargo:</label>
        <div>{{ form.cargo }}</div>
      </div>
      <div class="form-group">
          <label for="{{form.sexo.id_for_label}}">Sexo:</label>
          <div>{{ form.sexo }}</div>
        </div>
        <hr>
        <div class="form-group">
          <label for="{{form.estado.id_for_label}}">estado:</label>
          <div>{{ form.estado_fk }}</div>
        </div>
        <div class="form-group">
          <label for="{{form.cidade.id_for_label}}">cidade:</label>
          <div>{{ form.cidade_fk }}</div>
        </div>
      {% csrf_token %}
      <a href="{% url 'lista' %}" class="btn btn-secondary">Voltar</a>
      <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
  </div>
</div>
{% endblock %}
{% block javascript %}
<script>
  $(function(){
      $('#id_estado_fk').change(function(){
          const ajax_url = '{% url 'update_select_cidade' %}'
          let value = $(this).find(":selected").val()

          $.ajax({
            url: ajax_url,
            data: {state: value},
            dataType: 'json',
            success: function(data){
              $('#id_cidade_fk').html(data.html_cidade_option)
            }
          })
      });
  });
</script>
{% endblock %}

agenda/templates/deletar.html
{% extends "base.html" %}
<title>- Deletar</title>
{% load crispy_forms_tags %}
{% load static %}
<title>{% block title %} {{block.super}} - Excluir {%endblock%}</title>
{% block breadcrumb %}<li class="breadcrumb-item active" aria-current="page">Excluir</li>{% endblock %}
{% block content %}

<div class="container mt-5 pt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
          <div class="card-body">
            <form method="post">
              {% csrf_token %}
              <p class="card-text">Tem certeza que deseja excluir o contato <b>{{ deletar.nome }}</b> permanentemente ?</p>
              <a href="/" class="btn btn-secondary">Voltar</a>
              <button class="btn btn-danger">Excluir</button>
            </form>
         </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

agenda/templates/lista.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
<title>{% block title %} {{block.super}} - Listar {%endblock%}</title>

{% block content %}
<div class="container mt-5 pt-5">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="text-left mb-2">
            <a href="{% url 'cadastrar' %}" class="btn btn-primary">
              Cadastrar
            </a>
      </div>
      <table id="myTable2" class="table">
        <thead>
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th>celular</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th>Nome</th>
            <th>E-mail</th>
            <th>Telefone</th>
            <th>celular</th>
          </tr>
        </tfoot>
      </table>
      
    </div>
  </div>
</div>


{% endblock %}
{% block javascript %}
<script>
  $(document).ready( function () {
    $('#myTable2').DataTable({
      "ajax": "/person/json1/",
      "columns": [
        {"data": "nome"},
        {"data": "email"},
        {"data": "telefone"},
        {"data": "celular"}
      ]
    });
    $.ajax({
      url: "/person/json/",
      success: function(response) {
        console.log(response);
      }
    })


    $('#myTable2 tfoot th').each( function () {
        var title = $(this).text();
        $(this).html( '<input type="text" placeholder="Search '+title+'" />' );
    } );
 
    // DataTable
    var table = $('#myTable2').DataTable();
 
    // Apply the search
    table.columns().every( function () {
        var that = this;
 
        $( 'input', this.footer() ).on( 'keyup change', function () {
            if ( that.search() !== this.value ) {
                that
                    .search( this.value )
                    .draw();
            }
        } );
    } );




  });

  </script>
{% endblock javascript %}

agenda/templates/select_cidade_estado_option.html
{% for city in cities %}
    {% if forloop.first %}
    <option value="" selected="">---------</option>
    {% else %}
    <option value="{{ city.pk }}">{{ city.nom_cidade }}</option>
   {% endif %}
{% endfor %}